name: flutter_news_app
version: 1.0.1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  google_fonts: 2.2.0
  flutter_svg: ^1.0.1
  colorful_safe_area: ^0.3.0
  http: ^0.13.4
  webview_flutter: ^3.0.0
  flutter: 
    sdk: flutter
  firebase_core: ^1.13.0
  firebase_auth: ^3.3.8
  google_sign_in: 5.2.4
  cloud_firestore: ^3.1.9
  

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_launcher_icons: "^0.9.2"
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/launcher_icon.png"

flutter: 
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/icons/bottomNav/
    - assets/icons/settingIcons/

